### ISSUE TITLE
Not working with Members plugin

### ISSUE THREAD

**Issue by jasonbahl** [bradyvercher/gravity-forms-iframe#15]
I've got this plugin working great on 2 sites, but on another site I have the members plugin installed, and I cannot access the Settings page for this. When I de-activate the Members plugin, I can access the page. 

It appears that Gravity Forms itself has some code in the "webapi.php" file that attempts to solve this. Not sure if your plugin needs to do anything to make use of what's in Gravity Forms or if Gravity forms hasn't quite updated their GFWebAPI class properly. 

Anyway, thought I'd check in with ya'll in case you know anything.

**Comment by andywarren** [comment]
I too am having this occur. I just installed the plugin this morning, and after activation the iframe settings page is missing from the form settings. When I deactivate Members the iframe settings page reappears. I've checked in members, and all all Gravity Forms capabilities are granted, but something is still blocking this from showing up while Members is enabled. I've been looking over the `GFAddon` class, but I'm not real sure what to do with it. I don't see anything mentioning capabilites or role management.

Any solution to this?

**Comment by bradyvercher** [comment]
Hi @andywarren, I just pushed a commit that should hopefully fix this for you.

The `GFAddOn` class appears to have some properties to register capabilities, but it's not entirely clear how they work. From my testing, I'm always able to access the Iframe settings page as an admin -- with or without the Members plugin.

When switching to an Editor role with the Members plugin activated, the iframe settings page wasn't available. After defining the `gravityforms_iframe` capability in 7997935ba1f0640ace188d83f844b75037a64a90 and assigning it to the Editor role using Members (along with the the `gravityforms_edit_forms` capability), I was able to access and edit the iframe settings.

**Comment by andywarren** [comment]
This did indeed fix it, thank you! I agree with the `GFAddOn` class not being clear on this. I'm not near as well versed with PHP as you are, but I understand a little bit. I spent a couple hours today reading what documentation I could find on the Gravity Forms addon framework as well as Members, and came up with little to no specifics on how to accomplish adding in capabilities.

I'm going to share this post back on the issue I created on the Members Git repo as well just in case anyone else needs the solution. Thank you again!

**Comment by bradyvercher** [comment]
Glad to hear that took care of it! I did a quick search for some documentation myself and didn't come up with much, but did find a couple of official add-ons that use the capabilities this way.

I'll go ahead and tag a new release here in a few minutes.
