### ISSUE TITLE
Does this work on other HTML website?

### ISSUE THREAD

**Issue by vraghav** [bradyvercher/gravity-forms-iframe#17]
Thanks for the addon.

When I used the iframe on an html site, it showed as "Embedding is disabled for this form" on that 
particular page.

Am I doing anything wrong or do not support for html site. Please guide.

**Comment by bradyvercher** [comment]
When editing the form setting, you should see a checkbox to allow the form to be embedded. If that hasn't been enabled, it won't work. Once you do enable it, adding it to a static site should be fine, though.

There's a screenshot in the readme that shows the form settings tab: https://github.com/bradyvercher/gravity-forms-iframe#settings

**Comment by vraghav** [comment]
Thanks for the quick response, now the "Embedding is disabled for this form" is not there on the page.
But now even the form is also not visible.  

You can see the blank space in this page where I've inserted the iframe.
http://www.crocareers.in/clinical_research_course_registration/

Please assist.
