### ISSUE TITLE
Form not visible on the static website!

### ISSUE THREAD

**Issue by vraghav** [bradyvercher/gravity-forms-iframe#18]
Thanks for the quick response, now the "Embedding is disabled for this form" is not there on the page.
But now even the form is also not visible.

You can see the blank space in this page where I've inserted the iframe.
http://www.crocareers.in/clinical_research_course_registration/

Please assist.

**Comment by bradyvercher** [comment]
Sorry, but I can't provide support for this plugin. I did take a quick look and both the iframe and form are being output, but there's something on the WordPress site that's hiding the form itself, so that's where you'll need to look. Good luck!
