### ISSUE TITLE
Problems with Gravity Forms update 1.9.12.1 ?

### ISSUE THREAD

**Issue by amosarnold** [bradyvercher/gravity-forms-iframe#23]
Anyone having issues with plugin after Gravity Forms update 1.9.12.1 ? I can't get my iframe to show up correctly now. I have a few "Uncaught ReferenceError: jQuery is not defined"  errors.

Trying to get things to work on this page: https://emethgym.com/classes%20copy.html

**Comment by px-progers** [comment]
I experienced a similar issue with Gravity Forms 1.9.13. jQuery was not included on the page when viewing the embedded form as a logged in user. However, the form rendered fine when not logged in. I resolved the issue by printing jQuery myself in the `gravity-forms-iframe.php` override template, with the following block:

Right after opening `<body>` tag:

```php
<?php
// print jquery since gravityforms/form_display.php:1618 prints it only if jquery has not been enqueued
if (wp_script_is('jquery')) {
	wp_print_scripts('jquery');
}
?>
```

**Comment by bradyvercher** [comment]
I haven't been able to reproduce this, however it may be related to #27. Feel free to reopen this if that fix doesn't clear it up.

**Comment by amosarnold** [comment]
Thank you sir! That last commit seems to have fixed it. I had forms that weren't loading if they had any conditional field logic. I updated to the latest and it is working now.

Amos

**Comment by bradyvercher** [comment]
Very cool! Thanks for letting me know that fixed it. :+1:
