### ISSUE TITLE
iframe gravity forms have disappeared

### ISSUE THREAD

**Issue by tigertedd** [bradyvercher/gravity-forms-iframe#24]
I've used the Iframe plug in to embed a form in another site I manage. Someone filled int he form last night, so it was working then, but this morning, it has disappeared.

I added a field to the form this morning, I don't know if that might have made a difference, or if it had something to do with the recent Gravity Forms update.

This is the link to the page: http://www.prophlebotomytraining.co.uk/course-application-form/

There should be a form, but instead there is a big blank space. the code is still in the original page, so I can't think of any explanation for this. Any help is much appreciated.

**Comment by bradyvercher** [comment]
Hi @tigertedd, I took a look at that page and the form appears to be rendering just fine. Is it possible the site hosting the form was down this morning?

**Comment by tigertedd** [comment]
Hi Brady,

Sorry, I forgot to update the post. I worked out it was because I'd included a filed with conditions (an filed that appeared if the respondent answered 'other'). I'd previously worked out that it won't work with conditions, but forgotten. 

I should have amended my question to reflect that, but I'd still be interested to know if there is a solution to the conditions problem, or if I'm just doing something wrong. 

Thanks,

Edd

**Comment by bradyvercher** [comment]
I'm pretty sure things worked with conditional fields when I originally built the plugin, but I haven't followed Gravity Forms development very closely to know if anything has changed since then.

One thing that stands out is there are a few JavaScript issues when loading your form. From what I can tell, it's because GF outputs some scripts that attempt to use jQuery before it's actually loaded. Ideally, jQuery should be loaded before the form is output, so I'm not sure why it's loading way down in your footer.

**Comment by tigertedd** [comment]
That’s interesting. That could explain it. I’ll see if I can put the jquery stuff in the head and see if that works. That would be great if I can get the conditional rules to work.

Thanks

Edd

**Comment by tigertedd** [comment]
Hi Brady

I hope you’re doing well. You helped me out with an issue about 2 and a half years ago, and I was hoping you might help me out with another now.

I’m using your iframe plug in to put a form on the bottom of each page in this website, where it says: Book an appointment: http://www.heybaby4d.co.uk/

The problem I’m finding, and have found before, but was able to live with it, is that when I change the name of the sender in the forms settings, and the reply address, the default admin email and sender seems to remain.

This happens on all notifications. It’s fine on the admin notification, as we know what we’re looking out for. But it’s not so good on the customer notifications, as it looks very weird, like the email is coming from a completely different place.

I just wondered if this might be a symptom of it being part of an iframe, or if you could shed any light on it?

Kind regards

[cid:23AB4CE6-F144-42E8-B32F-8F24D3635FB7@Home]
Kind regards,

Edd Tillen

On 24 Aug 2015, at 20:35, Brady Vercher <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm pretty sure things worked with conditional fields when I originally built the plugin, but I haven't followed Gravity Forms development very closely to know if anything has changed since then.

One thing that stands out is there are a few JavaScript issues when loading your form. From what I can tell, it's because GF outputs some scripts that attempt to use jQuery before it's actually loaded. Ideally, jQuery should be loaded before the form is output, so I'm not sure why it's loading way down in your footer.
