### ISSUE TITLE
Error form_display.php on line 2250

### ISSUE THREAD

**Issue by jcesak** [bradyvercher/gravity-forms-iframe#27]
Hi Brady,
Your plugin worked like a charm embedding a GravityForm into an iframe on my site at http://www.isoho.org/. But, an error now appears in the iframe at the top of the form, "Warning: Invalid argument supplied for foreach() in /home/mcwr2015/public_html/wp-content/plugins/gravityforms/form_display.php on line 2250".

There is no error/warning when using the same form on a regular page (NOT embedded in an iframe).  See http://www.isoho.org/nominationform/.

Rob Harrell at gravityforms was unable to duplicate the issue on his server. He suggested that I contact you to see if you have some suggestions to address this problem.

Gravity Forms was just updated to Version 1.9.14 and WordPress is running on the latest Version 4.3.1.

Can you help? Thank you! Janet

**Comment by bradyvercher** [comment]
Hi Janet, I was able to reproduce this locally and it appears to be a long-standing issue in the template file. I'm surprised it hasn't been brought up before.

I'm hoping the commit I just pushed up should fix it. You can test by [downloading the development branch](https://github.com/bradyvercher/gravity-forms-iframe/archive/develop.zip) here.

Thanks for the report!

**Comment by jcesak** [comment]
Thank you, Brady!!!!

Perfect.

Janet

**Comment by bradyvercher** [comment]
Thanks for the update and glad to hear that took care of it!
