### ISSUE TITLE
Warning: Invalid argument supplied 

### ISSUE THREAD

**Issue by eileensiow** [bradyvercher/gravity-forms-iframe#28]
hi i have a new issue with the gravity form iframe plugin that i just saw today. i have checked the error with gravity forms and they told me that the error is coming from the iframe plugin. the following error appears:

Warning: Invalid argument supplied for foreach() in /home/olygenco/public_html/member/wp-content/plugins/gravityforms/form_display.php on line 2250

the error appears in the url:

http://bigdataworldshow.com/uae2015/form/

any solution for this?

thanks!!

**Comment by eileensiow** [comment]
i have solved this issue already.

**Comment by bradyvercher** [comment]
Glad to hear you got it worked out, @eileensiow! This should have been fixed in the [release I tagged](https://github.com/bradyvercher/gravity-forms-iframe/releases) a few hours ago. Did you do anything extra that wasn't covered in that version?

**Comment by swapnil2sutar** [comment]
@eileensiow  How you resoved. please share solution.
