### ISSUE TITLE
Add CSS to iframe

### ISSUE THREAD

**Issue by somethumb** [bradyvercher/gravity-forms-iframe#30]
I would like to adjust the styles in the iframe content (in my case Gravity Forms using WordPress). Is there a way to add to the CSS or add inline styles to the iframe content?

**Comment by bradyvercher** [comment]
You can add some styles in the footer of the iframe template. Something like this might do it:

```php
add_action( 'wp_footer', function() {
    if ( ! function_exists( 'is_gfiframe_template' ) || ! is_gfiframe_template() ) {
        return;
    }

    // Output styles.
} );
```

Otherwise, it might require a new custom action in the default template header.

**Comment by somethumb** [comment]
I like this idea. I added it currently into a new custom template, but I prefer the function way instead.

 

Thx!
