### ISSUE TITLE
Gravity Forms 2.0

### ISSUE THREAD

**Issue by uma-mantonio** [bradyvercher/gravity-forms-iframe#35]
This is a great add on, but updating to Gravity Forms 2.0 seems to conflict with the plugin. After updating to GF 2.0 I received this error "Fatal error: Access level to GFIframe_Addon::scripts() must be public in /wp-content/plugins/gravity-forms-iframe-master/includes/class-gfiframe-addon.php on line 183". Any chance there will be an update to work with GF 2.0?

**Comment by bradyvercher** [comment]
It sounds like you might have an older version of this add-on installed. Can you make sure you're running [v1.0.2](https://github.com/bradyvercher/gravity-forms-iframe/releases/tag/v1.0.2)?

**Comment by YesThatAllen** [comment]
Updating fixed the conflict with Gravityforms 2.01 on my site.

**Comment by uma-mantonio** [comment]
Yep, that was it. I had v1.0.1 installed and didn't know there was a v1.0.2. Thank you!
