### ISSUE TITLE
error include in wp-admin or sub domain in mutisite

### ISSUE THREAD

**Issue by foxpcteam** [bradyvercher/gravity-forms-iframe#5]
Hi,
i put the iframe in the wp-admin dashboard widget but the form don't be shown.
the same error in the front end.
i see the error is:
Uncaught ReferenceError: jQuery is not defined /gfembed/?f=1:39
Uncaught ReferenceError: jQuery is not defined /gfembed/?f=1:52

can you fix this?

Thanks

**Comment by bradyvercher** [comment]
The problem with jQuery may have been related to #27. I'm closing this out since there hasn't been any activity in over a year.
